### ISSUE TITLE
Your beamsearch decoder never gives result like aa or ll

### ISSUE THREAD

**Issue by menglin0320** [githubharald/CTCDecoder#10]
refering to https://github.com/githubharald/CTCDecoder/blob/master/src/BeamSearch.py
There seems to be a bug, I'm trying to debug now

**Comment by githubharald** [comment]
in case you think there is a bug, you have to provide the following data to make the problem re-producible:
* CSV file containing RNN output matrix
* list of characters contained in RNN output
* text file from which LM is trained (only if LM is used)

**Comment by menglin0320** [comment]
I tested it with this example
classes = 'ab'
mat = np.array([[0.8, 0, 0.2], [0.4, 0.0, 0.6], [0.8, 0, 0.2]])

And I realize the implementation is correct.

It's not a bug it's just the fact that this algorithm discourages same sequences, aka for the example above 'a' corresponds to 6 sequences: aaa,-aa,aa-,a--,--a,-a- but 'aa' only corresponds to 'a-a'. The model needs to be very well trained to be able to give result 'aa'.

**Comment by menglin0320** [comment]
Hmmm, this problem mitigates if every character in the sequence is longer.
