### ISSUE TITLE
Question about language model initialization

### ISSUE THREAD

**Issue by xuannianz** [githubharald/CTCDecoder#11]
Hi, Thanks for the sharing. I have a question in language model initialization function. Why do you set numSamples[c] to be len(classes) instead of 0?
https://github.com/githubharald/CTCDecoder/blob/d6a88ea5b3187fe5c81508d377b32eb6c860b868/src/LanguageModel.py#L31

**Comment by githubharald** [comment]
thanks for the hint, I fixed it.

**Comment by xuannianz** [comment]
It works well now, thanks.
