### ISSUE TITLE
beam_search with a beam_width=1

### ISSUE THREAD

**Issue by skalinin** [githubharald/CTCDecoder#26]
Hi!
Could you please tell, why does a beam_search with a beam_width equal to 1 not give the same result as best_path?

For example
```
import numpy as np
from ctc_decoder import best_path, beam_search

chars = 'ab'
mat = np.array([[0.8, 0, 0.2], [0.4, 0.0, 0.6], [0.8, 0, 0.2]])

print(f'Best path: "{best_path(mat, chars)}"')
print(f'Beam search: "{beam_search(mat, chars, beam_width=1)}"')
```
Gives:
Best path: "aa"
Beam search: "a"

Thanks!

**Comment by githubharald** [comment]
because it's not the same algorithm and is not expected to give the same results (even though TF says so in its documentation, which is wrong, see here: https://github.com/tensorflow/tensorflow/issues/21051).

**Comment by skalinin** [comment]
Thanks for the answer!
