### ISSUE TITLE
beam search

### ISSUE THREAD

**Issue by fangshuiyun** [githubharald/CTCDecoder#27]
Hi! I have a question! The result of "best_path" is normal or i want to,but when i used the "beam_search",the result is none or no output,is all blank! So what i meet? How to deal with?

**Comment by fangshuiyun** [comment]
> Hi! I have a question! The result of "best_path" is normal or i want to,but when i used the "beam_search",the result is none or no output,is all blank! So what i meet? How to deal with?

Now is OK!

**Comment by githubharald** [comment]
good to hear that it now works :-)
