### ISSUE TITLE
No module named 'editdistance'

### ISSUE THREAD

**Issue by anguslou** [githubharald/CTCDecoder#6]
I had installed editdistance at terminal successfully by:

pip install editdistance

And install requirements.txt with error as followed:

Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 5)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 5))

However no error message about editdistance.

But running main.py still get error message:

ModuleNotFoundError: No module named 'editdistance'

**Comment by githubharald** [comment]
pip install editdistance works for me - please ask the devs of editdistance for further help if you need it.
